language: csharp
solution: redisharp.sln
dotnet: 2.2.104
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
script:
  - dotnet restore
  - dotnet test
deploy:
  on:
    tags: true
    branch: master
  script:
    - dotnet pack -c Release -p:PackageVersion=$TRAVIS_TAG
    - dotnet nuget push src/RediSharp/bin/Release/RediSharp.*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json