language: csharp
solution: redisharp.sln
dotnet: 2.2.104
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
script:
  - dotnet clean
  - dotnet restore
  - dotnet build
  - dotnet test
deploy:
  provider: script
  skip_cleanup: true
  on:
    tags: true
    branch: master
  script: bash deploy.sh